export const listTypes = {
  ADD_LIST: 'ADD_LIST',
  DELETE_LIST: "DELETE_LIST",
  SELECT_LIST: "SELECT_LIST",
  CHANGE_PRODUCT_STATUS: "CHANGE_PRODUCT_STATUS",
  REMOVE_PRODUCT_LIST: "REMOVE_PRODUCT_LIST",
};
